CC = gcc -Wall -O1
PROGS =	practice01 \
		practice02 \
		practice03 \
		practice04 \
		practice05 \
		practice06 \
		practice07 \
		raspi_gpo \

all: $(PROGS)

clean:
	rm -f $(PROGS)
	rm -f data.csv
	rm -f a.out
